USE ADI_DB;

CREATE TABLE ROLE
(
    ID   INT         NOT NULL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL
);


CREATE TABLE EMPLEADO
(
    ID        INT         NOT NULL PRIMARY KEY,
    NOMBRE    VARCHAR(50) NOT NULL,
    APELLIDO  VARCHAR(50) NOT NULL,
    EMAIL     VARCHAR(50) NOT NULL,
    TELEFONO  VARCHAR(50) NOT NULL,
    DIRECCION VARCHAR(50) NOT NULL,
    ID_ROLE   INT         NOT NULL,
    FOREIGN KEY (ID_ROLE) REFERENCES ROLE (ID)
);

CREATE TABLE CLIENTE
(
    ID        INT         NOT NULL PRIMARY KEY,
    NOMBRE    VARCHAR(50) NULL,
    APELLIDO  VARCHAR(50) NULL,
    EMAIL     VARCHAR(50) NULL,
    TELEFONO  VARCHAR(50) NULL,
    DIRECCION VARCHAR(50) NULL
);

CREATE TABLE PROVEEDOR
(
    ID        INT         NOT NULL PRIMARY KEY,
    NOMBRE    VARCHAR(50) NULL,
    EMAIL     VARCHAR(50) NULL,
    TELEFONO  VARCHAR(50) NULL,
    DIRECCION VARCHAR(50) NULL
);

CREATE TABLE VENTA
(
    ID         INT  NOT NULL PRIMARY KEY,
    ID_CLIENTE INT  NOT NULL,
    FECHA      DATE NOT NULL,

    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID)
);

CREATE TABLE LINEA
(
    ID     INT         NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE CATEGORIA
(
    ID       INT         NOT NULL PRIMARY KEY,
    NAME     VARCHAR(50) NOT NULL,
    ID_LINEA INT         NOT NULL,
    FOREIGN KEY (ID_LINEA) REFERENCES LINEA (ID)
);

CREATE TABLE PRODUCTO
(
    ID           INT            NOT NULL PRIMARY KEY,
    NOMBRE       VARCHAR(50)    NOT NULL,
    PRECIO       DECIMAL(10, 2) NOT NULL,
    STOCK        INT            NOT NULL,
    ID_CATEGORIA INT            NOT NULL,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA (ID)
);

CREATE TABLE DETALLE_VENTA
(
    ID_VENTA    INT            NOT NULL,
    ID_PRODUCTO INT            NOT NULL,
    CANTIDAD    INT            NOT NULL,
    PRECIO      DECIMAL(10, 2) NOT NULL,
    DESCRIPCION VARCHAR(50)    NULL,
    FOREIGN KEY (ID_VENTA) REFERENCES VENTA (ID),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID)
);

CREATE TABLE COMPRA
(
    ID           INT  NOT NULL PRIMARY KEY,
    FECHA        DATE NOT NULL,
    ID_PROVEEDOR INT  NOT NULL,
    FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR (ID)
);

CREATE TABLE DETALLE_COMPRA
(
    ID_COMPRA   INT            NOT NULL,
    ID_PRODUCTO INT            NOT NULL,
    CANTIDAD    INT            NOT NULL,
    PRECIO      DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (ID_COMPRA) REFERENCES COMPRA (ID),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID)
);
